name = "EponymTuples"
uuid = "28d0dd7e-ae99-11e8-1574-ad8a33f43547"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.2.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
